# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 17:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=1000)),
                ('rating', models.IntegerField(max_length=10)),
                ('description', models.CharField(max_length=2000)),
                ('tags', models.CharField(max_length=1000)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlinkNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=2000)),
                ('owner', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.Blink')),
            ],
        ),
    ]
